{{- if .Values.middleware.corsEnabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "polkadot-rest-api.fullname" . }}-cors-headers
  labels:
    {{- include "polkadot-rest-api.labels" . | nindent 4 }}
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "OPTIONS"
    accessControlAllowHeaders:
      - "Content-Type"
    accessControlAllowOriginList:
      {{- range .Values.middleware.corsAllowOrigins }}
      - {{ . | quote }}
      {{- end }}
    accessControlMaxAge: 100
    addVaryHeader: true
{{- end }}
