apiVersion: v2
name: polkadot-rest-api
description: A Helm chart for Polkadot REST API

# Application chart
type: application

# Chart version - increment when making changes to the chart
version: 0.1.0

# Application version
appVersion: "0.1.0"
